### ISSUE TITLE
101. As a guest user, I want to create a new account.(5 hours)

### ISSUE THREAD

**Issue by akshay72222** [campusrope/campusropeweb#14]
Please discuss and finalise the requirements as needed.

## Requirements:

- First name (Required)
- Last name
- Select gender - male/female/
- Email id (Required)
- Password (Required)
- Confirm password (Required)
- I am not a robot simple checkbox
- Save and continue button - It will directly log in the user.
- Back button

## Task List

- Please share the old UI design of the Create New Account Form so that we can finalise it.
- Please try to define all the task of this issue in the form of a checklist and define its estimated time required for each task to be completed in this description.
- Please create a new issue and tag Rethna to sort out the I am not a robot problem.

## Acceptance Criteria

- The new user should be able to login with his credentials with all the standard error message if the email id or if the password is wrong.
- All the task are defined and marked as done.
- Make sure that the feature is production ready from your end. 
- Logging time should be less than 3 seconds.

## Sub-tasks

- [ ] Fix Recaptcha (1:20 hrs)

- [ ] Diagnose why logging in is taking 45 seconds.

- [ ] @faiyazuddeen  Please define other subtasks too, and mark it as done accordingly.

**Comment by akshay72222** [comment]
@faiyazuddeen Lets have the discussion here for this issue from now on.

**Comment by faiyazuddeen** [comment]
this is the signup screen we have
![Screenshot 2019-04-11 at 4 42 31 PM](https://user-images.githubusercontent.com/12336079/55953158-feab9780-5c78-11e9-80f2-e157d0241ca0.png)

**Comment by akshay72222** [comment]
Thanks. 
What were the three gender option we had?
Please change the title from "Sign up to" to "Sign Up"

**Comment by faiyazuddeen** [comment]
male,female and other

**Comment by akshay72222** [comment]
Okay.
The screen is fine.
Please add estimate time of this task and maybe you can define subtasks.

**Comment by faiyazuddeen** [comment]
where should i add the time

**Comment by akshay72222** [comment]
You can put total estimated time in the issue title like in issue 105 , 106 and put estimated time for each sub task in the description

**Comment by faiyazuddeen** [comment]
is there a way to estimate time

**Comment by akshay72222** [comment]
There are lots of factors but in end it can only be mastered with practice.

**Comment by akshay72222** [comment]
## Testing Diagnosis

### Changes

- [ ] On hover change the colour of the back button in sign up screen to #db3236.

- [ ] Add gender options in the sign up forum i.e.
Male
Female
Transgender
Others

- [ ] On hover change the colour of "Login with Google" button to #db3236 OR make it vice-versa.

- [ ] Remove Remember me checkbox

- [ ] Add a back button (arrow symbol) in the top left corner of the Sign in screen.

- [ ] In the Sign in screen there is a text which says "New to Campusrope ?" Make the R capital in the Rope.
