### ISSUE TITLE
102. Splash Screen UI

### ISSUE THREAD

**Issue by akshay72222** [campusrope/campusropeweb#16]
Font Used: Arial Rounded MT Bold

![S3](https://user-images.githubusercontent.com/22296552/55866607-50332400-5b9e-11e9-9ae3-5a3ff3925608.png)

## Task List
- Please try to define all the task of this issue in the form of a checklist and define its estimated time required for each task to be completed in this description.

## Acceptance Criteria

- All the task are defined and marked as done.
- Make sure that the feature is production ready from your end.

**Comment by faiyazuddeen** [comment]
define two appbar stages one before login and one aftet ( the one with icons)

**Comment by akshay72222** [comment]
## Testing Diagnosis

## Requirement not met

- [ ] Font

 to be used: Arial Rounded MT Bold

## Changes

- [ ] Lets try another colors for appbar as the current colour is similar to fb.
Try #1650cb

- [ ] Try to match the dimensions of "CampusRope" on widescreen splash screen appbar similar to given in sample.
![Current Sample](https://user-images.githubusercontent.com/22296552/56184077-7ccfbb80-6036-11e9-8060-a1a9fe3500a2.png)
![Expected sample](https://user-images.githubusercontent.com/22296552/56184078-7fcaac00-6036-11e9-9f0e-cb2a478586aa.png)

But once you change the dimensions of "CampusRope" it will look very big in mobile view. If that is the case then i will put a request for a new change as:
- Create a separate app bar for mobile view splash screen, so that it can be more customisable.

**Comment by akshay72222** [comment]
@faiyazuddeen

**Comment by faiyazuddeen** [comment]
what is the font size you want
i dont want to do two appbars for just font

**Comment by faiyazuddeen** [comment]
roboto font is the design specific font for material ui.you sure you want to change it

**Comment by faiyazuddeen** [comment]
closed mistakenly

**Comment by akshay72222** [comment]
(Arial Rounded MT Bold) is gonna be our brand logo font, so it has nothing to do with material UI.

**Comment by akshay72222** [comment]
I cannot specify the font size myself, you are the only one who can test and find out.

**Comment by faiyazuddeen** [comment]
okay

**Comment by faiyazuddeen** [comment]
what are you saying akshay.i dont understand

**Comment by faiyazuddeen** [comment]
how can i test font size

**Comment by faiyazuddeen** [comment]
now what we see if okay for me.is it big for you in mobile

**Comment by faiyazuddeen** [comment]
we dont have a design specification.so you need to show me a reference font size

**Comment by akshay72222** [comment]
## Changes

- [ ] Please change the colour of the app bar to #00235b.

- [ ] Please change the font of the CampusRope logo on the app bar to Calibri font. 
Use the given image for reference

![#00235b](https://user-images.githubusercontent.com/22296552/56343837-7af22d80-61d9-11e9-93c0-36f521419bd7.PNG)
![logo](https://user-images.githubusercontent.com/22296552/56343841-7ded1e00-61d9-11e9-8416-9f77c046a7d2.PNG)

**Comment by umarfarooq95** [comment]
![Screenshot from 2019-04-18 15-30-45](https://user-images.githubusercontent.com/21303105/56353493-20fc6280-61ef-11e9-876c-7f35b64cac0c.png)

**Comment by umarfarooq95** [comment]
Is this Okay Akshay

**Comment by akshay72222** [comment]
Calibri font looks better. 

## Change

- [ ] Make "Feeds, Home and Sign Up" in lower case and adjust its text size if needed.

**Comment by akshay72222** [comment]
@umarfarooq95 Which font have you used in the above CampusRope logo?

**Comment by umarfarooq95** [comment]
'Paytone One'. it similar to the calibri font.
